/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author ronaldo.pedro
 */
public class JFTelaPrincipal extends javax.swing.JFrame {

    String look_and_fell = ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

    /**
     * Creates new form JFTelaPrincipal
     */
    public JFTelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        lookandfell();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButtonSair = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemDepartamentos = new javax.swing.JMenuItem();
        jMenuItemEquipamentos = new javax.swing.JMenuItem();
        jMenuItemFiliais = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuCadastros1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jMenuCadastros.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuItemDepartamentos.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItemDepartamentos.setText("Departamentos");
        jMenuItemDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDepartamentosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemDepartamentos);

        jMenuItemEquipamentos.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItemEquipamentos.setText("Equipamentos");
        jMenuItemEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquipamentosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemEquipamentos);

        jMenuItemFiliais.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItemFiliais.setText("Filiais");
        jMenuItemFiliais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiliaisActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFiliais);

        jMenu2.setText("Perifericos");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItem3.setText("Teclado e Mouse");
        jMenu2.add(jMenuItem3);

        jMenuCadastros.add(jMenu2);

        jMenu4.setText("Outros");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItem5.setText("Marcas");
        jMenu4.add(jMenuItem5);

        jMenuCadastros.add(jMenu4);

        jMenu.add(jMenuCadastros);

        jMenuCadastros1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuCadastros1.setText("Configurações");
        jMenuCadastros1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu3.setText("Manutenção");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jMenuItem4.setText("Processadores");
        jMenu3.add(jMenuItem4);

        jMenuCadastros1.add(jMenu3);

        jMenu.add(jMenuCadastros1);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquipamentosActionPerformed
        // TODO add your handling code here:
        JDCadEquipamento equipamento = new JDCadEquipamento(null, rootPaneCheckingEnabled);
        equipamento.setLocationRelativeTo(null);
        equipamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemEquipamentosActionPerformed

    private void jMenuItemFiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiliaisActionPerformed
        // TODO add your handling code here:
        JFCadFilial filial = new JFCadFilial();
        filial.setLocationRelativeTo(null);
        filial.setVisible(true);
    }//GEN-LAST:event_jMenuItemFiliaisActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuItemDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDepartamentosActionPerformed
        // TODO add your handling code here:
        JDCadDepartamento departamento = new JDCadDepartamento(null, rootPaneCheckingEnabled);
        departamento.setLocationRelativeTo(null);
        departamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemDepartamentosActionPerformed

    public void lookandfell() {
        try {

            UIManager.setLookAndFeel(look_and_fell);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o tema = " + erro);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuCadastros1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemDepartamentos;
    private javax.swing.JMenuItem jMenuItemEquipamentos;
    private javax.swing.JMenuItem jMenuItemFiliais;
    // End of variables declaration//GEN-END:variables
}
